# Generated by Django 2.1.15 on 2021-04-11 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='producthunt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idtest', models.IntegerField()),
                ('testcol', models.CharField(max_length=3)),
                ('testcol1', models.CharField(max_length=3)),
            ],
        ),
    ]
