# Generated by Django 2.1.15 on 2021-04-26 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0002_productdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='auctiondetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('product_specifications', models.TextField()),
                ('current_bid', models.IntegerField()),
                ('closing_time', models.DateTimeField()),
            ],
        ),
    ]
