# Generated by Django 2.1.15 on 2021-05-02 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0002_auction_history_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_history',
            name='email',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='auction_history',
            name='phone_no',
            field=models.IntegerField(default=0),
        ),
    ]
