# Generated by Django 2.1.15 on 2021-05-02 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0003_auto_20210502_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction_history',
            name='auction_id',
        ),
    ]
