# Generated by Django 2.1.15 on 2021-05-13 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0004_remove_auction_history_auction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_history',
            name='phone_no',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_no',
            field=models.CharField(default='', max_length=30),
        ),
    ]
